### ISSUE TITLE
"pyvirtualdisplay.abstractdisplay.XStartTimeoutError"

### ISSUE THREAD

**Issue by Purukitto** [aayush1205/muCLIar#14]
```
mu -s "purple lamborgini"

Searching for your song |<class 'pyvirtualdisplay.abstractdisplay.XStartTimeoutError'> Failed to start X on display ":1001" (xdpyinfo check failed). <traceback object at 0x7ffaf434e288>
Traceback (most recent call last):
  File "/home/pulkitss/muCLIar/src/driver.py", line 67, in <module>
    Mus.search_song()
  File "/home/pulkitss/muCLIar/src/driver.py", line 44, in search_song
    obj.search()
  File "/home/pulkitss/muCLIar/src/main_search.py", line 38, in search
    display.start()            
  File "/home/pulkitss/miniconda3/envs/test/lib/python3.7/site-packages/pyvirtualdisplay/abstractdisplay.py", line 171, in start
    raise XStartTimeoutError(msg % d)
pyvirtualdisplay.abstractdisplay.XStartTimeoutError: Failed to start X on display ":1001" (xdpyinfo check failed).
Searching for your song /
```

My distro : Manjaro Linux

**Comment by Purukitto** [comment]
@aayush1205 @pranjaldatta review [this issue](ponty/PyVirtualDisplay/issues/42)

It seems removing `xdpyinfo` worked for mac OS at the very least

**Comment by aayush1205** [comment]
Did you try removing `xdpyinfo` yourself? It might be raising conflicts.

**Comment by Purukitto** [comment]
will check and update

**Comment by Purukitto** [comment]
I figured out the issue.
It was due to missing the neccessary server for `pvvirtualdisplay` server like xvfb.

Installing [`xorg-server-xvfb`](https://www.archlinux.org/packages/extra/x86_64/xorg-server-xvfb/) fixed the issues and the player works fine now.

@pranjaldatta Maybe this can be added in the installer?

**Comment by aayush1205** [comment]
Could you please mention what command worked for you. What package installer etc. It would be good for someone facing the same issue.

**Comment by Purukitto** [comment]
**For Arch**

I installed the following [package](https://www.archlinux.org/packages/extra/x86_64/xorg-server-xvfb/) to fix the issue.

Running `sudo pacman -S xorg-server-xvfb` installs the above and fixes the timeout error as mentioned before
