### ISSUE TITLE
Can't login using chrome

### ISSUE THREAD

**Issue by Purukitto** [aayush1205/muCLIar#15]
Unable to login using the "-c" command as of now

![Screenshot_20200131_121035](https://user-images.githubusercontent.com/49859368/73517932-fea4a000-4422-11ea-923a-c4340c2574cc.png)

**Comment by aayush1205** [comment]
Changing the -c from automation to manual. Google is blocking automated tasks hence not allowing login. Some security reason. Put this bug a high priority, I'll take a look asap.
