### ISSUE TITLE
Uninstaller Script

### ISSUE THREAD

**Issue by aayush1205** [aayush1205/muCLIar#19]
The repository creates driver files in the local bin of the user. Need to write an uninstaller that removes all of these files as well as the test env.

**Comment by Purukitto** [comment]
@aayush1205 Make the command so that is doesn't remove any package that has any other packages dependent on it unnecessarily

**Comment by Purukitto** [comment]
Also, consider adding a simple git sync as an update command

**Comment by aayush1205** [comment]
Noted.

**Comment by aayush1205** [comment]
Closing issue.
