### ISSUE TITLE
[Enhancement]Possibly integrate Youtube-DL 

### ISSUE THREAD

**Issue by drvladb** [aayush1205/muCLIar#22]
Instead of writing custom grab code possibly use [Youtube-dl](https://github.com/ytdl-org/youtube-dl/) and FFmpeg to get audio.

**Comment by aayush1205** [comment]
But then, even if I do manage to play the audio using YouTube dl, how would I allow the user to listen to his entire playlist. Let him login etc. Won't that functionality come with the browser? What is your opinion on this?
:

**Comment by aayush1205** [comment]
Please reopen the issue if you need anything else.
