### ISSUE TITLE
Code restructure

### ISSUE THREAD

**Issue by VishalBilagi** [aayush1205/muCLIar#33]
Can we work on restructuring the code. It is a little confusing to look at and hard track the control flow.

My first suggestion is to decouple input handling from the `main_search`.
Creating an object of `main_search` _(possibly rename this file, it is doing more than search)_ in `driver` and calling methods from here seems more logical.

**Comment by aayush1205** [comment]
Yes, why not? Are you willing to take it up?

**Comment by VishalBilagi** [comment]
Sure, I can work on that.

**Comment by aayush1205** [comment]
Closing the issue.
