### ISSUE TITLE
Display the Playlist Queue

### ISSUE THREAD

**Issue by aayush1205** [aayush1205/muCLIar#7]
MUCLIAR already shows which song is playing at the present moment. The proposed enhancement is to display at least the next five or ten songs to the user so that he could enjoy the next, prev functionality.

**Comment by aniketkishore100** [comment]
I will try and take up this issue.

**Comment by aayush1205** [comment]
Sure. Let me know how it goes. Assigning you to it.

**Comment by aayush1205** [comment]
@VishalBilagi Great job. Thanks!!
